# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-Server-Simple-Authen
version:      0.02
version_from: lib/HTTP/Server/Simple/Authen.pm
installdirs:  site
requires:
    Authen::Simple:                0.04
    HTTP::Server::Simple:          0.16
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
